src/Entity/Activity.php
<?php

/*
 * This file is part of the Kimai time-tracking app.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\Entity;

use App\Export\Annotation as Exporter;
use App\Validator\Constraints as Constraints;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use JMS\Serializer\Annotation as Serializer;
use OpenApi\Attributes as OA;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Table(name: 'kimai2_activities')]
#[ORM\Index(columns: ['visible', 'project_id'])]
#[ORM\Index(columns: ['visible', 'project_id', 'name'])]
#[ORM\Index(columns: ['visible', 'name'])]
#[ORM\Entity(repositoryClass: 'App\Repository\ActivityRepository')]
#[ORM\ChangeTrackingPolicy('DEFERRED_EXPLICIT')]
#[Serializer\ExclusionPolicy('all')]
#[Serializer\VirtualProperty('ProjectName', exp: 'object.getProject() === null ? null : object.getProject().getName()', options: [new Serializer\SerializedName('parentTitle'), new Serializer\Type(name: 'string'), new Serializer\Groups(['Activity'])])]
#[Serializer\VirtualProperty('ProjectAsId', exp: 'object.getProject() === null ? null : object.getProject().getId()', options: [new Serializer\SerializedName('project'), new Serializer\Type(name: 'integer'), new Serializer\Groups(['Activity', 'Team', 'Not_Expanded'])])]
#[Exporter\Order(['id', 'name', 'project', 'budget', 'timeBudget', 'budgetType', 'color', 'visible', 'comment', 'billable', 'number'])]
#[Exporter\Expose(name: 'project', label: 'project', exp: 'object.getProject() === null ? null : object.getProject().getName()')]
#[Constraints\Activity]
class Activity implements EntityWithMetaFields, EntityWithBudget
{
    use BudgetTrait;
    use ColorTrait;

    /**
     * Unique activity ID
     */
    #[ORM\Column(name: 'id', type: 'integer')]
    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: 'IDENTITY')]
    #[Serializer\Expose]
    #[Serializer\Groups(['Default'])]
    #[Exporter\Expose(label: 'id', type: 'integer')]
    private ?int $id = null;
    #[ORM\ManyToOne(targetEntity: Project::class)]
    #[ORM\JoinColumn(nullable: true, onDelete: 'CASCADE')]
    #[Serializer\Expose]
    #[Serializer\Groups(['Subresource', 'Expanded'])]
    #[OA\Property(ref: '#/components/schemas/ProjectExpanded')]
    private ?Project $project = null;
    /**
     * Name of this activity
     */
    #[ORM\Column(name: 'name', type: 'string', length: 150, nullable: false)]
    #[Assert\NotBlank]
    #[Assert\Length(min: 2, max: 150)]
    #[Serializer\Expose]
    #[Serializer\Groups(['Default'])]
    #[Exporter\Expose(label: 'name')]
    private ?string $name = null;
    /**
     * Description of this activity
     */
    #[ORM\Column(name: 'comment', type: 'text', nullable: true)]
    #[Serializer\Expose]
    #[Serializer\Groups(['Default'])]
    #[Exporter\Expose(label: 'comment')]
    private ?string $comment = null;
    /**
     * Whether this activity is visible and can be selected
     */
    #[ORM\Column(name: 'visible', type: 'boolean', nullable: false, options: ['default' => true])]
    #[Assert\NotNull]
    #[Serializer\Expose]
    #[Serializer\Groups(['Default'])]
    #[Exporter\Expose(label: 'visible', type: 'boolean')]
    private bool $visible = true;
    #[ORM\Column(name: 'billable', type: 'boolean', nullable: false, options: ['default' => true])]
    #[Assert\NotNull]
    #[Serializer\Expose]
    #[Serializer\Groups(['Default'])]
    #[Exporter\Expose(label: 'billable', type: 'boolean')]
    private bool $billable = true;
    /**
     * Meta fields registered with the activity
     *
     * @var Collection<ActivityMeta>
     */
    #[ORM\OneToMany(mappedBy: 'activity', targetEntity: ActivityMeta::class, cascade: ['persist'])]
    #[Serializer\Expose]
    #[Serializer\Groups(['Activity'])]
    #[Serializer\Type(name: 'array<App\Entity\ActivityMeta>')]
    #[Serializer\SerializedName('metaFields')]
    #[Serializer\Accessor(getter: 'getVisibleMetaFields')]
    private Collection $meta;
    /**
     * Teams with access to the activity
     *
     * @var Collection<Team>
     */
    #[ORM\JoinTable(name: 'kimai2_activities_teams')]
    #[ORM\JoinColumn(name: 'activity_id', referencedColumnName: 'id', onDelete: 'CASCADE')]
    #[ORM\InverseJoinColumn(name: 'team_id', referencedColumnName: 'id', onDelete: 'CASCADE')]
    #[ORM\ManyToMany(targetEntity: Team::class, inversedBy: 'activities', cascade: ['persist'])]
    #[Serializer\Expose]
    #[Serializer\Groups(['Activity'])]
    #[OA\Property(type: 'array', items: new OA\Items(ref: '#/components/schemas/Team'))]
    private Collection $teams;
    #[ORM\Column(name: 'invoice_text', type: 'text', nullable: true)]
    private ?string $invoiceText = null;
    #[ORM\Column(name: 'number', type: 'string', length: 10, nullable: true)]
    #[Assert\Length(max: 10)]
    #[Serializer\Expose]
    #[Serializer\Groups(['Default'])]
    #[Exporter\Expose(label: 'activity_number')]
    private ?string $number = null;

    public function __construct()
    {
        $this->meta = new ArrayCollection();
        $this->teams = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProject(): ?Project
    {
        return $this->project;
    }

    public function setProject(?Project $project): Activity
    {
        $this->project = $project;

        return $this;
    }

    public function setName(string $name): Activity
    {
        $this->name = $name;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setComment(?string $comment): Activity
    {
        $this->comment = $comment;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setVisible(bool $visible): Activity
    {
        $this->visible = $visible;

        return $this;
    }

    public function isGlobal(): bool
    {
        return $this->project === null;
    }

    public function isVisible(): bool
    {
        return $this->visible;
    }

    public function setBillable(bool $billable): void
    {
        $this->billable = $billable;
    }

    public function isBillable(): bool
    {
        return $this->billable;
    }

    /**
     * @return Collection|MetaTableTypeInterface[]
     */
    public function getMetaFields(): Collection
    {
        return $this->meta;
    }

    /**
     * @return MetaTableTypeInterface[]
     */
    public function getVisibleMetaFields(): array
    {
        $all = [];
        foreach ($this->meta as $meta) {
            if ($meta->isVisible()) {
                $all[] = $meta;
            }
        }

        return $all;
    }

    public function getMetaField(string $name): ?MetaTableTypeInterface
    {
        foreach ($this->meta as $field) {
            if (strtolower($field->getName()) === strtolower($name)) {
                return $field;
            }
        }

        return null;
    }

    public function setMetaField(MetaTableTypeInterface $meta): EntityWithMetaFields
    {
        if (null === ($current = $this->getMetaField($meta->getName()))) {
            $meta->setEntity($this);
            $this->meta->add($meta);

            return $this;
        }

        $current->merge($meta);

        return $this;
    }

    public function addTeam(Team $team): void
    {
        if ($this->teams->contains($team)) {
            return;
        }

        $this->teams->add($team);
        $team->addActivity($this);
    }

    public function removeTeam(Team $team): void
    {
        if (!$this->teams->contains($team)) {
            return;
        }
        $this->teams->removeElement($team);
        $team->removeActivity($this);
    }

    /**
     * @return Collection<Team>
     */
    public function getTeams(): Collection
    {
        return $this->teams;
    }

    public function getInvoiceText(): ?string
    {
        return $this->invoiceText;
    }

    public function setInvoiceText(?string $invoiceText): void
    {
        $this->invoiceText = $invoiceText;
    }

    public function setNumber(?string $number): void
    {
        $this->number = $number;
    }

    public function getNumber(): ?string
    {
        return $this->number;
    }

    public function __toString(): string
    {
        return $this->getName();
    }

    public function __clone()
    {
        if ($this->id !== null) {
            $this->id = null;
        }

        $currentTeams = $this->teams;
        $this->teams = new ArrayCollection();
        /** @var Team $team */
        foreach ($currentTeams as $team) {
            $this->addTeam($team);
        }

        $currentMeta = $this->meta;
        $this->meta = new ArrayCollection();
        /** @var ActivityMeta $meta */
        foreach ($currentMeta as $meta) {
            $newMeta = clone $meta;
            $newMeta->setEntity($this);
            $this->setMetaField($newMeta);
        }
    }
}

src/Entity/Role.php
<?php

/*
 * This file is part of the Kimai time-tracking app.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Table(name: 'kimai2_roles')]
#[ORM\UniqueConstraint(name: 'roles_name', columns: ['name'])]
#[ORM\Entity(repositoryClass: 'App\Repository\RoleRepository')]
#[ORM\ChangeTrackingPolicy('DEFERRED_EXPLICIT')]
#[UniqueEntity('name')]
class Role
{
    #[ORM\Column(name: 'id', type: 'integer')]
    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: 'IDENTITY')]
    private ?int $id = null;
    #[ORM\Column(name: 'name', type: 'string', length: 50, nullable: false)]
    #[Assert\NotNull]
    #[Assert\NotBlank]
    #[Assert\Length(min: 5, max: 50)]
    private ?string $name = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): Role
    {
        $this->name = strtoupper($name);

        return $this;
    }

    public function isUser(): bool
    {
        return $this->name === User::ROLE_USER;
    }
}

src/Form/Helper/CustomerHelper.php
<?php

/*
 * This file is part of the Kimai time-tracking app.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\Form\Helper;

use App\Configuration\SystemConfiguration;
use App\Entity\Customer;

final class CustomerHelper
{
    public const PATTERN_NAME = '{name}';
    public const PATTERN_NUMBER = '{number}';
    public const PATTERN_COMPANY = '{company}';
    public const PATTERN_COMMENT = '{comment}';
    public const PATTERN_SPACER = '{spacer}';
    public const SPACER = ' - ';

    private ?string $pattern = null;

    public function __construct(private readonly SystemConfiguration $configuration)
    {
    }

    public function getChoicePattern(): string
    {
        if ($this->pattern === null) {
            $this->pattern = $this->configuration->find('customer.choice_pattern');

            if ($this->pattern === null || stripos($this->pattern, '{') === false || stripos($this->pattern, '}') === false) {
                $this->pattern = self::PATTERN_NAME;
            }

            $this->pattern = str_replace(self::PATTERN_SPACER, self::SPACER, $this->pattern);
        }

        return $this->pattern;
    }

    public function getChoiceLabel(Customer $customer): string
    {
        $name = $this->getChoicePattern();
        $name = str_replace(self::PATTERN_NAME, $customer->getName(), $name);
        $name = str_replace(self::PATTERN_COMMENT, $customer->getComment() ?? '', $name);
        $name = str_replace(self::PATTERN_NUMBER, $customer->getNumber() ?? '', $name);
        $name = str_replace(self::PATTERN_COMPANY, $customer->getCompany() ?? '', $name);

        while (str_starts_with($name, self::SPACER)) {
            $name = substr($name, \strlen(self::SPACER));
        }

        while (str_ends_with($name, self::SPACER)) {
            $name = substr($name, 0, -\strlen(self::SPACER));
        }

        if ($name === '' || $name === self::SPACER) {
            $name = $customer->getName();
        }

        return substr($name, 0, 110);
    }
}

src/Form/Type/CustomerType.php
<?php

/*
 * This file is part of the Kimai time-tracking app.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\Form\Type;

use App\Entity\Customer;
use App\Form\Helper\CustomerHelper;
use App\Repository\CustomerRepository;
use App\Repository\Query\CustomerFormTypeQuery;
use App\Repository\Query\ProjectQuery;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\Options;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Custom form field type to select a customer.
 */
final class CustomerType extends AbstractType
{
    public function __construct(private CustomerHelper $customerHelper)
    {
    }

    public function getChoiceLabel(Customer $customer): string
    {
        return $this->customerHelper->getChoiceLabel($customer);
    }

    public function getChoiceAttributes(Customer $customer, $key, $value): array
    {
        return ['data-currency' => $customer->getCurrency()];
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            // documentation is for NelmioApiDocBundle
            'documentation' => [
                'type' => 'integer',
                'description' => 'Customer ID',
            ],
            'label' => 'customer',
            'class' => Customer::class,
            'choice_label' => [$this, 'getChoiceLabel'],
            'choice_attr' => [$this, 'getChoiceAttributes'],
            'query_builder_for_user' => true,
            'project_enabled' => false,
            'project_select' => 'project',
            'start_date_param' => '%begin_date%',
            'end_date_param' => '%end_date%',
            'ignore_date' => false,
            'project_visibility' => ProjectQuery::SHOW_VISIBLE,
            // @var Customer|null
            'ignore_customer' => null,
            // @var Customer|Customer[]|null
            'customers' => null,
            'pre_select_customer' => false,
        ]);

        $resolver->setDefault('query_builder', function (Options $options) {
            return function (CustomerRepository $repo) use ($options) {
                $query = new CustomerFormTypeQuery($options['customers']);

                if (true === $options['pre_select_customer']) {
                    $query->setAllowCustomerPreselect(true);
                }

                if (true === $options['query_builder_for_user']) {
                    $query->setUser($options['user']);
                }

                if (null !== $options['ignore_customer']) {
                    $query->setCustomerToIgnore($options['ignore_customer']);
                }

                return $repo->getQueryBuilderForFormType($query);
            };
        });

        $resolver->setDefault('api_data', function (Options $options) {
            if (false !== $options['project_enabled']) {
                $name = \is_string($options['project_enabled']) ? $options['project_enabled'] : 'customer';
                $routeParams = [$name => '%' . $name . '%', 'visible' => $options['project_visibility']];
                $emptyRouteParams = ['visible' => $options['project_visibility']];

                if (!$options['ignore_date']) {
                    if (!empty($options['start_date_param'])) {
                        $routeParams['start'] = $options['start_date_param'];
                        $emptyRouteParams['start'] = $options['start_date_param'];
                    }

                    if (!empty($options['end_date_param'])) {
                        $routeParams['end'] = $options['end_date_param'];
                        $emptyRouteParams['end'] = $options['end_date_param'];
                    }
                } else {
                    $routeParams['ignoreDates'] = 1;
                    $emptyRouteParams['ignoreDates'] = 1;
                }

                return [
                    'reload' => 'get_customers',
                    'select' => $options['project_select'],
                    'route' => 'get_projects',
                    'route_params' => $routeParams,
                    'empty_route_params' => $emptyRouteParams,
                ];
            }

            return [];
        });
    }

    public function buildView(FormView $view, FormInterface $form, array $options): void
    {
        $view->vars['attr'] = array_merge($view->vars['attr'], [
            'data-option-pattern' => $this->customerHelper->getChoicePattern(),
        ]);
    }

    public function getParent(): string
    {
        return EntityType::class;
    }
}

templates/customer/actions.html.twig
{% macro customer(customer, view, options) %}
    {% import "macros/widgets.html.twig" as widgets %}
    {% set event = actions(app.user, 'customer', view, {'customer': customer}) %}
    {% if view == 'index' or view == 'custom' %}
        {{ widgets.table_actions(event.actions) }}
    {% else %}
        {{ widgets.page_actions(event.actions) }}
    {% endif %}
{% endmacro %}

templates/customer/delete.html.twig
{% extends kimai_context.modalRequest ? 'form.html.twig' : 'base.html.twig' %}

{% block main %}
    {% set params = {
        '%records%': stats.counter,
        '%duration%': stats.duration|duration
    } %}
    {{ include(kimai_context.modalRequest ? 'default/_form_delete_modal.html.twig' : 'default/_form_delete.html.twig', {
        'message': ("delete_warning.short_stats"|trans(params) ~ "admin_entity.delete_confirm"|trans),
        'form': form,
        'delete_item_name': customer.name,
        'used': (stats.counter > 0),
        'back': path('admin_customer')
    }) }}
{% endblock %}

templates/customer/details.html.twig
{% extends 'base.html.twig' %}
{% import "macros/widgets.html.twig" as widgets %}

{% block main %}
    {% set can_edit = is_granted('edit', customer) %}

    {% embed '@theme/embeds/card.html.twig' %}
        {% import "macros/widgets.html.twig" as widgets %}
        {% block box_attributes %}id="customer_details_box"{% endblock %}
        {% block box_title %}
            {{ widgets.label_dot(customer.name, customer.color) }}
            {% if customer.company is not empty %} &ndash; {{ customer.company }}{% endif %}
        {% endblock %}
        {% block box_tools %}
            {% if can_edit %}
                {{ widgets.card_tool_button('edit', {'class': 'modal-ajax-form open-edit', 'title': 'action.edit', 'url': path('admin_customer_edit', {'id': customer.id})}) }}
            {% endif %}
        {% endblock %}
        {% block box_body_class %}p-0{% endblock %}
        {% block box_body %}
            {% if customer.comment is not empty %}
                <div class="comment p-3">
                    {{ customer.comment|comment2html(true) }}
                </div>
            {% endif %}
            <table class="table table-hover dataTable">
                {% if not customer.visible %}
                    <tr class="{{ widgets.class_customer_row(customer, now) }}">
                        <th>{{ 'visible'|trans }}</th>
                        <td>{{ widgets.label_boolean(customer.visible) }}</td>
                    </tr>
                {% endif %}
                {% if not customer.billable %}
                    <tr>
                        <th>{{ 'billable'|trans }}</th>
                        <td colspan="3">
                            {{ widgets.label_boolean(customer.billable) }}
                        </td>
                    </tr>
                {% endif %}
                {% if customer.address is not empty %}
                    <tr>
                        <th>{{ 'address'|trans }}</th>
                        <td>{{ customer.address|nl2br }}</td>
                    </tr>
                {% endif %}
                {% if customer.country is not empty %}
                    <tr>
                        <th>{{ 'country'|trans }}</th>
                        <td>{{ customer.country|country_name }}</td>
                    </tr>
                {% endif %}
                {% if customer.contact is not empty %}
                    <tr>
                        <th>{{ 'contact'|trans }}</th>
                        <td>{{ customer.contact }}</td>
                    </tr>
                {% endif %}
                {% if customer.phone is not empty %}
                    <tr>
                        <th>{{ 'phone'|trans }}</th>
                        <td><a href="tel:{{ customer.phone }}">{{ customer.phone }}</a></td>
                    </tr>
                {% endif %}
                {% if customer.mobile is not empty %}
                    <tr>
                        <th>{{ 'mobile'|trans }}</th>
                        <td><a href="tel:{{ customer.mobile }}">{{ customer.mobile }}</a></td>
                    </tr>
                {% endif %}
                {% if customer.email is not empty %}
                    <tr>
                        <th>{{ 'email'|trans }}</th>
                        <td><a href="mailto:{{ customer.email }}">{{ customer.email }}</a></td>
                    </tr>
                {% endif %}
                {% if customer.homepage is not empty %}
                    <tr>
                        <th>{{ 'homepage'|trans }}</th>
                        <td><a href="{{ customer.homepage }}" target="_blank">{{ customer.homepage|replace({'https://': '', 'http://': ''}) }}</a></td>
                    </tr>
                {% endif %}
                {% if customer.fax is not empty %}
                    <tr>
                        <th>{{ 'fax'|trans }}</th>
                        <td>{{ customer.fax }}</td>
                    </tr>
                {% endif %}
                {% if customer.timezone is not empty %}
                    <tr>
                        <th>{{ 'timezone'|trans }}</th>
                        <td>{{ customer_now|date_time }} ({{ customer.timezone }})</td>
                    </tr>
                {% endif %}
                {% if customer.currency is not empty %}
                    <tr>
                        <th>{{ 'currency'|trans }}</th>
                        <td>{{ customer.currency }}</td>
                    </tr>
                {% endif %}
                {% if is_granted('details', customer) %}
                    {% if customer.number is not empty %}
                        <tr>
                            <th>{{ 'number'|trans }}</th>
                            <td>{{ customer.number }}</td>
                        </tr>
                    {% endif %}
                    {% if customer.vatId is not empty %}
                        <tr>
                            <th>{{ 'vat_id'|trans }}</th>
                            <td>{{ customer.vatId }}</td>
                        </tr>
                    {% endif %}
                {% endif %}
                {% for metaField in customer.visibleMetaFields|filter(field => field.defined)|sort((a, b) => a.order <=> b.order) %}
                    <tr>
                        <th>{{ metaField.label|trans }}</th>
                        <td>{{ widgets.form_type_value(metaField.type, metaField.value, customer) }}</td>
                    </tr>
                {% endfor %}
            </table>
        {% endblock %}
    {% endembed %}

    {{ render(controller('App\\Controller\\CustomerController::projectsAction', {'customer': customer.id, 'page': 1})) }}

    {% if can_edit %}
        {{ include('embeds/rates-table.html.twig', {'id': 'customer_rates_box', 'entity': customer, 'create_url': path('admin_customer_rate_add', {'id': customer.id}), 'delete_route': 'delete_customer_rate', 'currency': customer.currency, 'edit_route': 'admin_customer_rate_edit'}) }}
    {% endif %}

    {% if stats is not null %}
        {{ include('embeds/budgets.html.twig', {'entity': customer, 'stats': stats, 'currency': customer.currency}) }}
    {% endif %}

    {% for controller in boxes %}
        {{ render(controller(controller, {'customer': customer, 'page': 1})) }}
    {% endfor %}

    {% if teams is not null %}
        {% set options = {'teams': teams, 'team': team} %}
        {% if is_granted('permissions', customer) %}
            {% set options = options|merge({'route_create': path('customer_team_create', {'id': customer.id}), 'route_edit': path('admin_customer_permissions', {'id': customer.id})}) %}
        {% endif %}
        {{ include('embeds/teams.html.twig', options) }}
    {% endif %}

    {% if comments is not null %}
        {% set options = {'form': commentForm, 'comments': comments} %}
        {% if can_edit %}
            {% set options = options|merge({'route_pin': 'customer_comment_pin', 'route_delete': 'customer_comment_delete', 'csrf_delete': 'customer.delete_comment', 'csrf_pin': 'customer.pin_comment'}) %}
        {% endif %}
        {{ include('embeds/comments.html.twig', options) }}
    {% endif %}

{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script type="text/javascript">
        document.addEventListener('kimai.initialized', function() {
            KimaiReloadPageWidget.create('kimai.customerTeamUpdate kimai.customerUpdate kimai.teamUpdate kimai.projectTeamUpdate kimai.rateUpdate');
        });
    </script>
{% endblock %}

templates/customer/edit.html.twig
{% extends kimai_context.modalRequest ? 'form.html.twig' : 'base.html.twig' %}

{% block main %}
    {% set formEditTemplate = kimai_context.modalRequest ? 'default/_form_modal.html.twig' : 'default/_form.html.twig' %}
    {% set formOptions = {
        'title': (customer.id is null ? 'create'|trans : 'edit'|trans({}, 'actions')),
        'form': form,
        'back': path('admin_customer')
    } %}
    {% embed formEditTemplate with formOptions %}
        {% block form_body %}
            <div class="row">
                <div class="col-md-9">
                    {{ form_row(form.name) }}
                </div>
                <div class="col-md-3">
                    {{ form_row(form.color) }}
                </div>
            </div>
            {{ form_row(form.comment) }}
            {{ form_row(form.address) }}
            <div class="row">
                <div class="col-md-4">
                    {{ form_row(form.company) }}
                </div>
                <div class="col-md-4">
                    {{ form_row(form.number) }}
                </div>
                <div class="col-md-4">
                    {{ form_row(form.vatId) }}
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    {{ form_row(form.country) }}
                </div>
                <div class="col-md-4">
                    {{ form_row(form.currency) }}
                </div>
                <div class="col-md-4">
                    {{ form_row(form.timezone) }}
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    {{ form_row(form.contact) }}
                </div>
                <div class="col-md-4">
                    {{ form_row(form.email) }}
                </div>
                <div class="col-md-4">
                    {{ form_row(form.homepage) }}
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    {{ form_row(form.mobile) }}
                </div>
                <div class="col-md-4">
                    {{ form_row(form.phone) }}
                </div>
                <div class="col-md-4">
                    {{ form_row(form.fax) }}
                </div>
            </div>
            {% if form.budgetType is defined %}
                <div class="row">
                    {% if form.budget is defined %}
                        <div class="col-md-4">
                            {{ form_row(form.budget) }}
                        </div>
                    {% endif %}
                    {% if form.timeBudget is defined %}
                        <div class="col-md-4">
                            {{ form_row(form.timeBudget) }}
                        </div>
                    {% endif %}
                    <div class="col-md-4">
                        {{ form_row(form.budgetType) }}
                    </div>
                </div>
            {% endif %}
            {% if form.teams is defined %}
            <div class="row">
                <div class="col-12">
                    {{ form_row(form.teams) }}
                </div>
            </div>
            {% endif %}
            <div class="row">
                <div class="col-md-6">
                    {{ form_row(form.visible) }}
                </div>
                <div class="col-md-6">
                    {{ form_row(form.billable) }}
                </div>
            </div>
            {% if form.metaFields is defined and form.metaFields is not empty %}
                {{ form_row(form.metaFields) }}
            {% endif %}
            {% embed '@theme/embeds/collapsible.html.twig' with {id: 'customer_invoice_settings'} %}
                {% import "macros/widgets.html.twig" as widgets %}
                {% block title %}{{ 'invoices'|trans }}{% endblock %}
                {% block body %}
                    {% if form.invoiceTemplate is defined %}
                        {{ form_row(form.invoiceTemplate) }}
                    {% endif %}
                    {% if form.invoiceText is defined %}
                        {{ form_row(form.invoiceText) }}
                    {% endif %}
                {% endblock %}
            {% endembed %}
            {{ form_rest(form) }}
        {% endblock %}
    {% endembed %}
{% endblock %}

templates/customer/permissions.html.twig
{% extends kimai_context.modalRequest ? 'form.html.twig' : 'base.html.twig' %}

{% block main %}
    {{ include(kimai_context.modalRequest ? 'default/_form_modal.html.twig' : 'default/_form.html.twig', {
        'title': ('permissions'|trans({}, 'actions')) ~ ': ' ~ customer.name,
        'form': form,
        'back': path('customer_details', {'id': customer.id})
    }) }}
{% endblock %}

templates/customer/rates.html.twig
{% extends kimai_context.modalRequest ? 'form.html.twig' : 'base.html.twig' %}

{% block main %}
    {{ include(kimai_context.modalRequest ? 'default/_form_modal.html.twig' : 'default/_form.html.twig', {
        'title': customer.name,
        'form': form,
        'back': path('admin_customer')
    }) }}
{% endblock %}