src/Entity/Role.php
<?php

/*
 * This file is part of the Kimai time-tracking app.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Table(name: 'kimai2_roles')]
#[ORM\UniqueConstraint(name: 'roles_name', columns: ['name'])]
#[ORM\Entity(repositoryClass: 'App\Repository\RoleRepository')]
#[ORM\ChangeTrackingPolicy('DEFERRED_EXPLICIT')]
#[UniqueEntity('name')]
class Role
{
    #[ORM\Column(name: 'id', type: 'integer')]
    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: 'IDENTITY')]
    private ?int $id = null;
    #[ORM\Column(name: 'name', type: 'string', length: 50, nullable: false)]
    #[Assert\NotNull]
    #[Assert\NotBlank]
    #[Assert\Length(min: 5, max: 50)]
    private ?string $name = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): Role
    {
        $this->name = strtoupper($name);

        return $this;
    }

    public function isUser(): bool
    {
        return $this->name === User::ROLE_USER;
    }
}

templates/macros/breadcrumb.html.twig
{% macro breadcrumb(breadcrumbs) %}
    {% from '@theme/components/breadcrumb.html.twig' import breadcrumb %}
    <div class="btn-list">
    {{ breadcrumb(breadcrumbs, 'arrows') }}
    </div>
{% endmacro %}

templates/macros/charts.html.twig
{# ------------------------------------------------------------------------------ #}
{# DOUNGHNUT CHART - @see https://www.chartjs.org/docs/2.9.4/charts/doughnut.html #}
{# ------------------------------------------------------------------------------ #}

{#
    options = {'label': 'label', 'title': string|null, 'footer': string|null, 'legend': {'display': false}}
#}
{% macro doughnut_javascript(options) %}
    <script type="text/javascript">
        function doughnutChartOptions() {
            return {
                maintainAspectRatio: false,
                responsive: true,
                cutoutPercentage: 40,
                animation: {
                    animateRotate: true
                },
                plugins: {
                    {% if options.legend is defined and options.legend is iterable %}
                    legend: {{ options.legend|json_encode|raw }},
                    {% endif %}
                    tooltip: {
                        callbacks: {
                            label: function(tooltipItem) {
                                const tooltipData = tooltipItem.dataset.realData[tooltipItem.dataIndex];
                                return ' ' + tooltipData['{{ options.label|default('label') }}'];
                            },
                            afterTitle: function(tooltipItems) {
                                return ' ';
                            },
                            {% if options.title is defined and options.title is not empty %}
                            title: function(tooltipItems) {
                                const tooltipItem = tooltipItems[0];
                                const tooltipData = tooltipItem.dataset.realData[tooltipItem.dataIndex];
                                return ' ' + tooltipData['{{ options.title }}'];
                            },
                            {% endif %}
                            {% if options.footer is defined and options.footer is not empty %}
                            beforeFooter: function(tooltipItems) {
                                return ' ';
                            },
                            footer: function(tooltipItems) {
                                const tooltipItem = tooltipItems[0];
                                const tooltipData = tooltipItem.dataset.realData[tooltipItem.dataIndex];
                                return tooltipData['{{ options.footer }}'];
                            },
                            {% endif %}
                        }
                    }
                },
            };
        }
    </script>
{% endmacro %}

{#
    id          = 'name'
    labels      = ['Foo', 'Bar']
    dataset     = [{name: '', color: '', duration: 0, rate: 0}]
    options     = {'height: '100px', 'renderEvent': 'kimai.initialized'}
#}
{% macro doughnut_chart(id, labels, dataset, options) %}
    {% set height = options.height|default(config('theme.chart.height') ~ 'px') %}
    {% set bgColor = config('theme.chart.background_color') %}
    <div class="{{ config('chart-class') }}" style="position: relative;">
        <canvas id="{{ id }}" style="height: {{ height }}; width: 100%;"></canvas>
    </div>
    <script type="text/javascript">
        document.addEventListener('{{ options.renderEvent|default('kimai.initialized') }}', function() {
            new Chart(
                document.getElementById("{{ id }}").getContext("2d"), {
                    type: 'doughnut',
                    data: {
                        {% if labels is not empty %}
                        labels: {{ labels|json_encode|raw }},
                        {% endif %}
                        datasets: [
                            {
                                backgroundColor: [
                                    {% for entry in dataset %}
                                    '{{ entry.color|default(bgColor) }}',
                                    {% endfor %}
                                ],
                                data: [
                                    {% for entry in dataset %}
                                    {{ entry.value }}
                                    {% if not loop.last %},{% endif %}
                                    {% endfor %}
                                ],
                                realData: {{ dataset|json_encode|raw }},
                            }
                        ]
                    },
                    options: Object.assign(doughnutChartOptions(),{{ options|json_encode|raw }})
                }
            );
        });
    </script>
{% endmacro %}

{# ------------------------------------------------------------------- #}
{# BAR CHART - @see https://www.chartjs.org/docs/2.9.4/charts/bar.html #}
{# ------------------------------------------------------------------- #}

{#
    options = {'label': 'label', 'title': string|null, 'footer': string|null, 'legend': {'display': false}, 'onclick': {'url': string, 'replacer': {'name': 'value'}}}
#}
{% macro bar_javascript(options) %}
    <script type="text/javascript">
        function barChartOptions() {
            return {
                maintainAspectRatio: true,
                responsive: true,
                barPercentage: 0.5,
                categoryPercentage: 1.0,
                scales: {
                    x: {
                        gridLines: {
                            display: false
                        }
                    },
                    y: {
                        ticks: {
                            beginAtZero: true,
                        },
                        gridLines: {
                            display: true,
                            color: '{{ config('theme.chart.grid_color') }}',
                            lineWidth: 1
                        }
                    }
                },
                plugins: {
                    {% if options.legend is defined and options.legend is iterable %}
                    legend: {{ options.legend|json_encode|raw }},
                    {% endif %}
                    tooltip: {
                        titleSpacing: 0,
                        titleMarginBottom: 0,
                        footerMarginTop: 0,
                        callbacks: {
                            label: function(tooltipItem) {
                                const tooltipData = tooltipItem.dataset.realData[tooltipItem.dataIndex];
                                return ' ' + tooltipData['{{ options.label|default('label') }}'];
                            },
                            afterTitle: function(tooltipItems) {
                                return ' ';
                            },
                            {% if options.title is defined and options.title is not empty %}
                            title: function(tooltipItems) {
                                const tooltipItem = tooltipItems[0];
                                const tooltipData = tooltipItem.dataset.realData[tooltipItem.dataIndex];
                                return ' ' + tooltipData['{{ options.title }}'];
                            },
                            {% endif %}
                            {% if options.footer is defined and options.footer is not empty %}
                            beforeFooter: function(tooltipItems) {
                                return ' ';
                            },
                            footer: function(tooltipItems) {
                                const tooltipItem = tooltipItems[0];
                                const tooltipData = tooltipItem.dataset.realData[tooltipItem.dataIndex];
                                return tooltipData['{{ options.footer }}'];
                            },
                            {% endif %}
                        }
                    },
                },
                {% if options.onclick is defined and options.onclick.url is defined %}
                onClick: function(event, elements, chart) {
                    if (elements.length !== 1) {
                        return;
                    }
                    const element = elements[0];
                    const data = this.data.datasets[element.datasetIndex].realData[element.index];
                    let url = '{{ options.onclick.url|raw }}';
                    {% if options.onclick.replacer is defined %}
                        {% for replacer, field in options.onclick.replacer %}
                        url = url.replace(/{{ replacer }}/, data['{{ field }}']);
                        {% endfor %}
                        document.location = url;
                    {% endif %}
                },
                {% endif %}
            };
        }
    </script>
{% endmacro %}

{#
    id          = 'name'
    labels      = ['Foo', 'Bar']
    datasets    = [[{'value': 1234, 'tooltip': '1234€', 'color': ''}]]
    options     = {'height: '100px', 'renderEvent': 'kimai.initialized'}
#}
{% macro bar_chart(id, labels, datasets, options) %}
    {% set height = options.height|default(config('theme.chart.height') ~ 'px') %}
    {% set bgColor = config('theme.chart.background_color') %}
    <div class="{{ config('chart-class') }}" style="position: relative;">
        <canvas id="{{ id }}" style="height: {{ height }}; width: 100%;"></canvas>
    </div>
    <script type="text/javascript">
        document.addEventListener('{{ options.renderEvent|default('kimai.initialized') }}', function() {
            new Chart(
                document.getElementById('{{ id }}').getContext("2d"), {
                    type: '{{ options.type|default('bar') }}',
                    data: {
                        {% if labels is not empty %}
                        labels: {{ labels|json_encode|raw }},
                        {% endif %}
                        datasets: [
                            {% for dataset in datasets %}
                            {
                                backgroundColor: [
                                    {% for entry in dataset %}
                                    '{{ entry.color|default(bgColor) }}',
                                    {% endfor %}
                                ],
                                data: [
                                    {% for entry in dataset %}
                                    {{ entry.value }},
                                    {% endfor %}
                                ],
                                realData: {{ dataset|json_encode|raw }},
                            },
                            {% endfor %}
                        ]
                    },
                    options: Object.assign(barChartOptions(),{{ options|json_encode|raw }})
                }
            );
        });
    </script>
{% endmacro %}

templates/macros/progressbar.html.twig
{% macro progressbar_full(options) %}
    {% set max = options['max'] ?? 0 %}
    {% set current = options['current'] ?? 0 %}
    {% set open = options['open'] ?? null %}
    {% set reverseColors = options['reverseColors'] ?? false %}
    {% set formatter = options['format'] ?? null %}
    {% set currency = options['currency'] ?? null %}
    {% set percentDecimals = options['decimals'] ?? 1 %}
    {% set transPercentOpen = options['trans_percent_open'] ?? 'stats.percentUsedLeft' %}
    {% set transPercentSpent = options['trans_percent_spent'] ?? 'stats.percentUsed' %}
    {% set outerClass = options['class'] ?? '' %}
    {% if formatter == 'duration' %}
        {% set currentFormatted = current|duration %}
        {% set maxFormatted = max|duration %}
        {% set openFormatted = open is not null ? open|duration : null %}
    {% elseif formatter == 'money' and currency is not null %}
        {% set currentFormatted = current|money(currency) %}
        {% set maxFormatted = max|money(currency) %}
        {% set openFormatted = open is not null ? open|money(currency) : null %}
    {% else %}
        {% set currentFormatted = current %}
        {% set maxFormatted = max %}
        {% set openFormatted = open is not null ? open : null %}
    {% endif %}
    {% set percentReached = 0 %}
    {% if max > 0 %}
        {% set percentReached = (current / (max / 100)) %}
    {% endif %}
    {% set width = percentReached|number_format(1, '.', '') %}

    {% if width > 100 %}
        {% set width = 100 %}
    {% endif %}

    <div class="progress-group {{ outerClass }}">
        <div class="progress-title">
            <span class="progress-text">
                {{ currentFormatted }}
            </span>
            <span class="progress-number text-end">
                <strong>
                    {{ maxFormatted }}
                </strong>
            </span>
        </div>
        <div class="progress">
            <div class="progress-bar {{ progressbar_color(percentReached, reverseColors) }}" role="progressbar" aria-valuenow="{{ width }}" aria-valuemin="0" aria-valuemax="100" style="width: {{ width }}%"></div>
        </div>
        {% if open is not null and open > 0 %}
            <small>{{ transPercentOpen|trans({'%percent%': percentReached|number_format(percentDecimals), '%left%': openFormatted}) }}</small>
        {% else %}
            <small>{{ transPercentSpent|trans({'%percent%': percentReached|number_format(percentDecimals)}) }}</small>
        {% endif %}
    </div>
{% endmacro %}

{% macro progressbar(max, current, title, subTitle, reverseColors) %}
    {% set percentReached = 0 %}
    {% if max > 0 %}
        {% set percentReached = (current / (max / 100)) %}
    {% endif %}
    {% set width = percentReached|number_format(1, '.', '') %}

    {% if width > 100 %}
        {% set width = 100 %}
    {% endif %}

    <div class="progress-group">
        <div class="progress-title">
            <span class="progress-text">
                {{ title }}
                {% if percentReached >= 0 and subTitle is not empty %} &ndash; {{ percentReached|number_format(2) }}%{% endif %}
            </span>
            <span class="progress-number text-end">
                {% if percentReached >= 0 and subTitle is empty %}
                    {{ percentReached|number_format(2) }}%
                {% elseif subTitle is not empty %}
                    {{ subTitle }}
                {% endif %}
            </span>
        </div>
        <div class="progress">
            <div class="progress-bar {{ progressbar_color(percentReached, reverseColors) }}" role="progressbar" aria-valuenow="{{ width }}" aria-valuemin="0" aria-valuemax="100" style="width: {{ width }}%"></div>
        </div>
    </div>
{% endmacro %}

{% macro progressbar_small(max, current, leftValue, leftFormatted, reverseColors) %}
    {% set percentReached = 0 %}
    {% if max > 0 %}
        {% set percentReached = (current / (max / 100)) %}
    {% endif %}
    {% set width = percentReached|number_format(1, '.', '') %}

    {% if width > 100 %}
        {% set width = 100 %}
    {% endif %}

    <div class="progress-group">
        <div class="progress progress-sm">
            <div class="progress-bar {{ progressbar_color(percentReached, reverseColors) }}" role="progressbar" aria-valuenow="{{ width }}" aria-valuemin="0" aria-valuemax="100" style="width: {{ width }}%"></div>
        </div>
        {% if leftValue is not null and leftValue > 0 %}
            <small>{{ 'stats.percentUsedLeft'|trans({'%percent%': percentReached|number_format(0), '%left%': leftFormatted}) }}</small>
        {% else %}
            <small>{{ 'stats.percentUsed'|trans({'%percent%': percentReached|number_format(0)}) }}</small>
        {% endif %}
    </div>
{% endmacro %}

{#
    @param \App\Model\BudgetStatisticModelInterface budgetStatisticModel
    @param string currency
#}
{% macro progressbar_budget(budgetStatisticModel, currency) %}
    {% if budgetStatisticModel.hasBudget() %}
        {% set options = {
            'max': budgetStatisticModel.getBudget(),
            'current': budgetStatisticModel.getBudgetSpent(),
            'open': (budgetStatisticModel.getBudgetOpen()),
            'format': 'money',
            'currency': currency,
        } %}
        {% if budgetStatisticModel.isMonthlyBudget() %}
            {% set options = options|merge({
                'trans_percent_open': 'stats.percentUsedLeft_month',
                'trans_percent_spent': 'stats.percentUsed_month',
            }) %}
        {% endif %}
        {{ _self.progressbar_full(options) }}
    {% endif %}
{% endmacro %}

{#
    @param \App\Model\BudgetStatisticModelInterface budgetStatisticModel
#}
{% macro progressbar_timebudget(budgetStatisticModel) %}
    {% if budgetStatisticModel.hasTimeBudget() %}
        {% set options = {
            'max': budgetStatisticModel.getTimeBudget(),
            'current': budgetStatisticModel.getTimeBudgetSpent(),
            'open': (budgetStatisticModel.getTimeBudgetOpen()),
            'format': 'duration',
        } %}
        {% if budgetStatisticModel.isMonthlyBudget() %}
            {% set options = options|merge({
                'trans_percent_open': 'stats.percentUsedLeft_month',
                'trans_percent_spent': 'stats.percentUsed_month',
            }) %}
        {% endif %}
        {{ _self.progressbar_full(options) }}
    {% endif %}
{% endmacro %}

templates/macros/search.html.twig
{% macro searchButton(form) %}
    <input type="hidden" name="_token" value="{{ csrf_token('search') }}">
    <div class="btn-group me-auto">
        {% if form.vars.data.bookmark %}
            <button type="submit" id="setDefaultQuery" name="setDefaultQuery" class="btn btn-outline-secondary" data-toggle="tooltip" title="{{ 'set_as_default'|trans }}">
                {{ icon('bookmarked', true) }}
                {{ 'action.save'|trans }}
            </button>
            <a class="btn btn-icon btn-outline-warning" href="?_token={{ csrf_token('search') }}&removeDefaultQuery={{ form.vars.data.bookmark.name }}" data-toggle="tooltip" title="{{ 'remove_default'|trans }}" id="removeDefaultQuery">
                {{ icon('delete', true) }}
            </a>
        {% else %}
            <button type="submit" id="setDefaultQuery" name="setDefaultQuery" class="btn btn-outline-secondary" data-toggle="tooltip" title="{{ 'set_as_default'|trans }}">
                {{ icon('bookmark', true) }}
                {{ 'action.save'|trans }}
            </button>
        {% endif %}
        {% if form.vars.data.countFilter() > 0 and not form.vars.data.isBookmarkSearch() %}
            <button type="submit" id="resetSearchFilter" name="resetSearchFilter" class="btn btn-icon btn-outline-secondary" data-toggle="tooltip" title="{{ 'remove_filter'|trans }}">{{ icon('cancel', true) }}</button>
        {% endif %}
    </div>
    <button type="submit" name="performSearch" value="performSearch" class="performSearch btn btn-primary ms-auto" data-type="submit">{{ 'search'|trans }}</button>
{% endmacro %}

templates/macros/status.html.twig
{% macro status(title, color) %}
    {% from '@theme/components/status.html.twig' import status %}
    {% set options = {} %}
    {% if color %}{% set options = options|merge({'color': color}) %}{% endif %}
    {{ status(title, options) }}
{% endmacro %}

{% macro status_duration(duration) %}
    {{ _self.status(duration, 'azure') }}
{% endmacro %}

{% macro status_money(money) %}
    {{ _self.status(money, 'blue') }}
{% endmacro %}

{% macro status_count(counter) %}
    {{ _self.status(counter, 'teal') }}
{% endmacro %}

templates/macros/webloader.html.twig
{% macro init_frontend_loader() %}
    {% set configurations = javascript_configurations(app.user)|merge({
        login: path('login'),
        direction: tabler_bundle.rightToLeft ? 'rtl' : 'ltr',
        first_dow_iso: iso_day_by_name(app.user.firstDayOfWeek),
    }) %}
    <script type="text/javascript">
        window.addEventListener('load', function() {
            const loader = new KimaiWebLoader({{ configurations|json_encode|raw }},{{ javascript_translations()|json_encode|raw }});
            window.kimai = loader.getKimai();
        });
    </script>
{% endmacro %}